language: java

matrix:
  include:
    # TODO add MacOS and OpenJDK 9 to matrix when Travis CI adds support
    - os: linux
      dist: xenial
      group: edge
      jdk: oraclejdk9
      sudo: required

# The 'build' task runs most things, including test, check, & static analysis
install: true
script:
  - ./gradlew -u -S --no-daemon --no-parallel build jacocoAggregateReport coveralls
  - ./gradlew -u -S --no-daemon --no-parallel :npm_run_lint-js

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
