os: Visual Studio 2017 # Windows Server 2016
install:
  # Java 9 work around
  # https://github.com/appveyor/ci/issues/1186
  - cinst jdk9 -version 9.0.1.11 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk9
  - SET PATH=C:\jdk9\bin;%PATH%

  - java -version
  - gradlew.bat --version
# The 'build' task runs most things, including test, check, & static analysis
build: off
test_script: gradlew.bat -u -S --no-daemon --no-parallel build
cache:
  - C:\Users\appveyor\.npm
  - C:\Users\appveyor\.gradle
